In [1]:
import pandas as pd

In [11]:
df_survival = pd.read_csv('gender_submission.csv')

In [12]:
df_survival.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [15]:
df_info = pd.read_csv('test.csv')

In [16]:
df_info.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [17]:
df_main = pd.merge(df_survival, df_info, on="PassengerId")

**Analyze survival rate by gender**

In [18]:
gender_survival = df_main.groupby("Sex")["Survived"].mean()

In [19]:
print("Survival rate by gender:")
gender_survival

Survival rate by gender:

Sex
female    1.0
male      0.0
Name: Survived, dtype: float64

**Analyze survival rate by passenger class**

In [20]:
pclass_survival = df_main.groupby("Pclass")["Survived"].mean()

In [21]:
print("Survival rate by passenger class:")
pclass_survival

Survival rate by passenger class:

Pclass
1    0.467290
2    0.322581
3    0.330275
Name: Survived, dtype: float64

**Survival rate by gender and class combined**

In [22]:
gender_pclass_survival = df_main.groupby(["Sex", "Pclass"])["Survived"].mean() * 100

In [23]:
print("Survival percentage by gender and passenger class:")
gender_pclass_survival

Survival percentage by gender and passenger class:

Sex     Pclass
female  1         100.0
        2         100.0
        3         100.0
male    1           0.0
        2           0.0
        3           0.0
Name: Survived, dtype: float64